package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/dailytravel/x/sales/graph/model"
)

// CreateContact is the resolver for the createContact field.
func (r *mutationResolver) CreateContact(ctx context.Context, input model.NewContact) (*model.Contact, error) {
	panic(fmt.Errorf("not implemented: CreateContact - createContact"))
}

// UpdateContact is the resolver for the updateContact field.
func (r *mutationResolver) UpdateContact(ctx context.Context, id string, input model.UpdateContact) (*model.Contact, error) {
	panic(fmt.Errorf("not implemented: UpdateContact - updateContact"))
}

// DeleteContact is the resolver for the deleteContact field.
func (r *mutationResolver) DeleteContact(ctx context.Context, id string) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: DeleteContact - deleteContact"))
}

// DeleteContacts is the resolver for the deleteContacts field.
func (r *mutationResolver) DeleteContacts(ctx context.Context, ids []string) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: DeleteContacts - deleteContacts"))
}

// Contacts is the resolver for the contacts field.
func (r *queryResolver) Contacts(ctx context.Context, args map[string]interface{}) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: Contacts - contacts"))
}

// Contact is the resolver for the contact field.
func (r *queryResolver) Contact(ctx context.Context, id string) (*model.Contact, error) {
	panic(fmt.Errorf("not implemented: Contact - contact"))
}

// ContactCreated is the resolver for the contactCreated field.
func (r *subscriptionResolver) ContactCreated(ctx context.Context) (<-chan *model.Contact, error) {
	panic(fmt.Errorf("not implemented: ContactCreated - contactCreated"))
}

// ContactUpdated is the resolver for the contactUpdated field.
func (r *subscriptionResolver) ContactUpdated(ctx context.Context) (<-chan *model.Contact, error) {
	panic(fmt.Errorf("not implemented: ContactUpdated - contactUpdated"))
}

// ContactDeleted is the resolver for the contactDeleted field.
func (r *subscriptionResolver) ContactDeleted(ctx context.Context) (<-chan *model.Contact, error) {
	panic(fmt.Errorf("not implemented: ContactDeleted - contactDeleted"))
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
