package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/dailytravel/x/sales/graph/model"
)

// CreateQuote is the resolver for the createQuote field.
func (r *mutationResolver) CreateQuote(ctx context.Context, input *model.NewQuote) (*model.Quote, error) {
	panic(fmt.Errorf("not implemented: CreateQuote - createQuote"))
}

// UpdateQuote is the resolver for the updateQuote field.
func (r *mutationResolver) UpdateQuote(ctx context.Context, id string, input model.UpdateQuote) (*model.Quote, error) {
	panic(fmt.Errorf("not implemented: UpdateQuote - updateQuote"))
}

// DeleteQuote is the resolver for the deleteQuote field.
func (r *mutationResolver) DeleteQuote(ctx context.Context, id string) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: DeleteQuote - deleteQuote"))
}

// DeleteQuotes is the resolver for the deleteQuotes field.
func (r *mutationResolver) DeleteQuotes(ctx context.Context, ids []string) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: DeleteQuotes - deleteQuotes"))
}

// Quotes is the resolver for the quotes field.
func (r *queryResolver) Quotes(ctx context.Context, args map[string]interface{}) (*model.Quotes, error) {
	panic(fmt.Errorf("not implemented: Quotes - quotes"))
}

// Quote is the resolver for the quote field.
func (r *queryResolver) Quote(ctx context.Context, id string) (*model.Quote, error) {
	panic(fmt.Errorf("not implemented: Quote - quote"))
}

// ID is the resolver for the id field.
func (r *quoteResolver) ID(ctx context.Context, obj *model.Quote) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Owner is the resolver for the owner field.
func (r *quoteResolver) Owner(ctx context.Context, obj *model.Quote) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Owner - owner"))
}

// Contact is the resolver for the contact field.
func (r *quoteResolver) Contact(ctx context.Context, obj *model.Quote) (*model.Contact, error) {
	panic(fmt.Errorf("not implemented: Contact - contact"))
}

// ValidUntil is the resolver for the valid_until field.
func (r *quoteResolver) ValidUntil(ctx context.Context, obj *model.Quote) (int, error) {
	panic(fmt.Errorf("not implemented: ValidUntil - valid_until"))
}

// Metadata is the resolver for the metadata field.
func (r *quoteResolver) Metadata(ctx context.Context, obj *model.Quote) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// Billing is the resolver for the billing field.
func (r *quoteResolver) Billing(ctx context.Context, obj *model.Quote) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: Billing - billing"))
}

// CreatedAt is the resolver for the created_at field.
func (r *quoteResolver) CreatedAt(ctx context.Context, obj *model.Quote) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - created_at"))
}

// UpdatedAt is the resolver for the updated_at field.
func (r *quoteResolver) UpdatedAt(ctx context.Context, obj *model.Quote) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updated_at"))
}

// CreatedBy is the resolver for the created_by field.
func (r *quoteResolver) CreatedBy(ctx context.Context, obj *model.Quote) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreatedBy - created_by"))
}

// UpdatedBy is the resolver for the updated_by field.
func (r *quoteResolver) UpdatedBy(ctx context.Context, obj *model.Quote) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdatedBy - updated_by"))
}

// Quote returns QuoteResolver implementation.
func (r *Resolver) Quote() QuoteResolver { return &quoteResolver{r} }

type quoteResolver struct{ *Resolver }
