package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	"time"

	"github.com/dailytravel/x/workspace/graph/model"
)

// ID is the resolver for the id field.
func (r *portfolioResolver) ID(ctx context.Context, obj *model.Portfolio) (string, error) {
	return obj.ID.Hex(), nil
}

// Boards is the resolver for the boards field.
func (r *portfolioResolver) Boards(ctx context.Context, obj *model.Portfolio) ([]*model.Board, error) {
	panic(fmt.Errorf("not implemented: Boards - boards"))
}

// Metadata is the resolver for the metadata field.
func (r *portfolioResolver) Metadata(ctx context.Context, obj *model.Portfolio) (map[string]interface{}, error) {
	return obj.Metadata, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *portfolioResolver) CreatedAt(ctx context.Context, obj *model.Portfolio) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - created_at"))
}

// UpdatedAt is the resolver for the updated_at field.
func (r *portfolioResolver) UpdatedAt(ctx context.Context, obj *model.Portfolio) (string, error) {
	return time.Unix(int64(obj.UpdatedAt.T), 0).Format(time.RFC3339), nil
}

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context, id string) (*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: Portfolio - portfolio"))
}

// Portfolios is the resolver for the portfolios field.
func (r *queryResolver) Portfolios(ctx context.Context) ([]*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: Portfolios - portfolios"))
}

// Portfolio returns PortfolioResolver implementation.
func (r *Resolver) Portfolio() PortfolioResolver { return &portfolioResolver{r} }

type portfolioResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *portfolioResolver) Owner(ctx context.Context, obj *model.Portfolio) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Owner - owner"))
}
func (r *portfolioResolver) CreatedBy(ctx context.Context, obj *model.Portfolio) (*model.User, error) {
	return &model.User{
		Model: model.Model{
			ID: obj.CreatedBy,
		},
	}, nil
}
func (r *portfolioResolver) UpdatedBy(ctx context.Context, obj *model.Portfolio) (*model.User, error) {
	return &model.User{
		Model: model.Model{
			ID: obj.UpdatedBy,
		},
	}, nil
}
