package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/dailytravel/x/hrm/graph/model"
)

// ID is the resolver for the id field.
func (r *payrollResolver) ID(ctx context.Context, obj *model.Payroll) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// PayDate is the resolver for the pay_date field.
func (r *payrollResolver) PayDate(ctx context.Context, obj *model.Payroll) (string, error) {
	panic(fmt.Errorf("not implemented: PayDate - pay_date"))
}

// Metadata is the resolver for the metadata field.
func (r *payrollResolver) Metadata(ctx context.Context, obj *model.Payroll) (map[string]interface{}, error) {
	return obj.Metadata, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *payrollResolver) CreatedAt(ctx context.Context, obj *model.Payroll) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - created_at"))
}

// UpdatedAt is the resolver for the updated_at field.
func (r *payrollResolver) UpdatedAt(ctx context.Context, obj *model.Payroll) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updated_at"))
}

// CreatedBy is the resolver for the created_by field.
func (r *payrollResolver) CreatedBy(ctx context.Context, obj *model.Payroll) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedBy - created_by"))
}

// UpdatedBy is the resolver for the updated_by field.
func (r *payrollResolver) UpdatedBy(ctx context.Context, obj *model.Payroll) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedBy - updated_by"))
}

// Payroll returns PayrollResolver implementation.
func (r *Resolver) Payroll() PayrollResolver { return &payrollResolver{r} }

type payrollResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *payrollResolver) User(ctx context.Context, obj *model.Payroll) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}
