package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/dailytravel/x/reporting/graph/model"
)

// DeleteLog is the resolver for the deleteLog field.
func (r *mutationResolver) DeleteLog(ctx context.Context, id string) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: DeleteLog - deleteLog"))
}

// Log is the resolver for the log field.
func (r *queryResolver) Log(ctx context.Context, id string) (*model.Log, error) {
	panic(fmt.Errorf("not implemented: Log - log"))
}

// Logs is the resolver for the logs field.
func (r *queryResolver) Logs(ctx context.Context, args map[string]interface{}) (*model.Logs, error) {
	panic(fmt.Errorf("not implemented: Logs - logs"))
}
