package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/dailytravel/x/community/graph/model"
)

// FindCommentByID is the resolver for the findCommentByID field.
func (r *entityResolver) FindCommentByID(ctx context.Context, id string) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: FindCommentByID - findCommentByID"))
}

// FindFollowByID is the resolver for the findFollowByID field.
func (r *entityResolver) FindFollowByID(ctx context.Context, id string) (*model.Follow, error) {
	panic(fmt.Errorf("not implemented: FindFollowByID - findFollowByID"))
}

// FindReactionByID is the resolver for the findReactionByID field.
func (r *entityResolver) FindReactionByID(ctx context.Context, id string) (*model.Reaction, error) {
	panic(fmt.Errorf("not implemented: FindReactionByID - findReactionByID"))
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: FindUserByID - findUserByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
