package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/dailytravel/x/cms/graph/model"
)

// CreateReaction is the resolver for the createReaction field.
func (r *mutationResolver) CreateReaction(ctx context.Context, input model.NewReaction) (*model.Reaction, error) {
	panic(fmt.Errorf("not implemented: CreateReaction - createReaction"))
}

// UpdateReaction is the resolver for the updateReaction field.
func (r *mutationResolver) UpdateReaction(ctx context.Context, id string, input model.UpdateReaction) (*model.Reaction, error) {
	panic(fmt.Errorf("not implemented: UpdateReaction - updateReaction"))
}

// Reaction is the resolver for the reaction field.
func (r *queryResolver) Reaction(ctx context.Context, object string, typeArg string) (*model.Reaction, error) {
	panic(fmt.Errorf("not implemented: Reaction - reaction"))
}

// Reactions is the resolver for the reactions field.
func (r *queryResolver) Reactions(ctx context.Context, args map[string]interface{}) (*model.Reactions, error) {
	panic(fmt.Errorf("not implemented: Reactions - reactions"))
}
